### ISSUE TITLE
Add support for udev_monitor_*

### ISSUE THREAD

**Issue by hlieberman** [dcuddeback/libudev-rs#1]
libudev exposes functionality around monitoring for device changes that seem to be in libudev-sys, but aren't wrapped in libudev-rs.  Would it be possible to have them added?

**Comment by dcuddeback** [comment]
@hlieberman Yes, absolutely. This should be added.

**Comment by dcuddeback** [comment]
@hlieberman I pushed up a commit that adds support for `udev_monitor_*`: https://github.com/dcuddeback/libudev-rs/commit/430fcb20c18c0acb09a58817aff52ed2606e22ec I'll release it to crates.io later this week after I add some documentation. Please feel free to reopen this issue if there are any issues with the implementation.
